### ISSUE TITLE
Improve leaderboard command

### ISSUE THREAD

**Issue by Indicardo** [bolt-rip/issues#1]
Show winrate, wins and losses as well by doing `!lb wins` or `!lb losses`

**Comment by unixfox** [comment]
From discord: `have a leaderboard for the most games played`. by ref

**Comment by Pablete1234** [comment]
Having arbitrary scoreboards would be a nice one:
`!lb wins/losses` or `!lb score*wins/losses`
i'm guessing the obvious variables to allow are wins, losses, games_played and score (elo), idk if there's anything more that should be exposed
