### ISSUE TITLE
Ditch out mc-oauth.net

### ISSUE THREAD

**Issue by Indicardo** [bolt-rip/issues#2]
What the title says, ideally it should be done through the lobby as that will keep banned and BAC banned users from registering

**Comment by unixfox** [comment]
Mojang when switching to Microsoft accounts will probably release an oauth so you won't need to use mc-oauth anymore but just ask the player to visit a link then confirm the request on Microsoft page.

Mojang announcement: https://www.minecraft.net/en-us/article/java-edition-moving-house
