### ISSUE TITLE
Handle players leaving, automate polling after match start

### ISSUE THREAD

**Issue by Indicardo** [bolt-rip/issues#3]
- [x] Feature 1
- [x] Feature 2

#### Feature 1

Once the match has started and a player leaves (or doesn't join the match right away) a timer starts and if it reaches 2 minutes that player should be submitted to an API endpoint (which results in a queue ban and a double loss). If one or more players leaves, a global variable called "invalidate" is changed from the default `false` to `true`, and will be sent along the match finish endpoint (which results in users winning/losing half the ELO they were supposed to get)

#### Feature 2

Currently, Ingame keeps polling the API for a match every 30 seconds. Once it finds one, though, it stops polling and proceeds to cycle and handle the match. Because it stops polling, if that match is cancelled (and thus never started) that server could be assigned again and the server wouldn't cycle/handle the match.

The solution is quite easy: keep polling matches, even after finding one, and override the current one if the polled match is different, even if that means ending the match.

**Comment by Pablete1234** [comment]
- Using /ready when the team doesn't have the minimum players online shouldn't be possible
- If a player leaves, the team automatically unreadies
- If the match start countdown reaches 0 (the match would start) and players are missing, force-finish the match (no win/loss of elo) and temp ban the leavers from q
 - If during the match someone leaves (and is out of the match for over 2 minutes) the player is banned from q and receives double loss (as described above by indicado)
