### ISSUE TITLE
Spin up a temporary node in Canada

### ISSUE THREAD

**Issue by Picajoluna** [bolt-rip/issues#5]
Google Cloud finally has available server cloud space in Canada, which is where the OCC dedicated machine is hosted. The Bolt servers are currently hosted on Google Cloud in NYC.  Players on Ranked servers get redirected through the OCC bungee (Canada) to the Ranked (NYC) servers, thus adding a 15 ms delay.  This is a suspected source of various complaints over PvP and knockback on ranked.

@unixfox will try to spin up a server in Canada soon for a slight latency improvement (on the order of 5ms he said?), so players can check for potential improvement in pvp/kb.

**Comment by unixfox** [comment]
We plan to switch to OVH Kubernetes and due to that I won't try to deploy a server in Google Cloud.
