### ISSUE TITLE
Prioritize allowing competing players to join full servers

### ISSUE THREAD

**Issue by Picajoluna** [bolt-rip/issues#6]
If the server is full (i.e. there are more obs on than competing players and total list of players amounts to 20), then players who are meant to compete in the actual match may not be able to join.

The plugin could randomly kick an observer (and allow ops / staff to bypass the count) in favor of allowing competing players to join.  It's likely best to keep the number of observers down to devote as many resources as possible to the match.

**Comment by unixfox** [comment]
I prefer that the competing players can bypass the slot limit than kicking random obs. Just like op can bypass the limit.

I think it's easier to implement and this won't really affect the performance of a server if there are 2 or 3 additional players than the fixed slot size.

**Comment by Pugzy** [comment]
Should be fixed in https://github.com/Pugzy/ingame/commit/29b0eb7f88a2f9fa178843c305880514d9f2bc0b.
