### ISSUE TITLE
Increase player render distance

### ISSUE THREAD

**Issue by Pugzy** [bolt-rip/issues#7]
Currently, players disappear on certain maps because they're out of range. The distance probably just needs upping

**Comment by unixfox** [comment]
Do we need to increase the view-distance?

**Comment by Pablete1234** [comment]
not the chunks, the players. Entity-specific configs exist for how close/far away entities should be sent or removed to other players

**Comment by unixfox** [comment]
@TiTo418 Can you copy the settings for that from the event servers?

The file is I think here: https://github.com/bolt-rip/config-pgm/blob/master/sportpaper.yml

![2020-10-10_21-29](https://user-images.githubusercontent.com/4016501/95662456-9b791a80-0b26-11eb-802f-f7ccfe3ef797.png)

**Comment by Pugzy** [comment]
Should be fixed in https://github.com/bolt-rip/config-pgm/commit/6a1453d13011f04ecc3726c9420f758afa0214da.
